/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * recherche_client.java
 *
 * Created on 19 octobre 2015, 13:34:57
 */
package gerer_application;

import Operations.Operation;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author yacho
 */
public class recherche_client extends javax.swing.JFrame {

    /** Creates new form recherche_client */
    public recherche_client(int i) {
        super("Details des articles remis a lemployé N° : " + i);
        Object[][] donnes = recherche_client(i);
        initComponents();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                donnes,
                new String[]{
                    "ID Client", "ID Article", "Nom Article", "Categorie", "Quantite"
                }));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBounds(new java.awt.Rectangle(400, 100, 200, 200));
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gerer_application.Gerer_Application.class).getContext().getResourceMap(recherche_client.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(413, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    /* public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    new recherche_client().setVisible(true);
    }
    });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public Object[][] recherche_client(int id) {
        Statement s;
        ResultSet rs;
        Operation op = new Operation();
        Connection con = op.conect();
        Object[][] donnes = new Object[100][5];
        try {
            s = con.createStatement();
            rs = s.executeQuery("select * from Client where ID_Client LIKE '" + id + "%'");
            int i = 0;
            if (rs.next()) {
                while (rs.next()) {
                    for (i = 0; i < donnes.length + 1; i++) {
                        donnes[i][0] = rs.getInt(1);
                        donnes[i][1] = rs.getInt(2);
                        donnes[i][2] = rs.getString(3);
                        donnes[i][3] = rs.getString(4);
                        donnes[i][4] = rs.getInt(5);
                        rs.next();
                    }
                }
            } else {
                donnes = null;
            }
        } catch (Exception e) {
        }
        return donnes;
    }
}
